

name: Build and Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  env:
    AWS_REGION: "us-east-1"
    REPOSITORY_NAME: "INSERT_REPOSITORY_NAME_HERE"
    IMAGE_TAG: ${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPOSITORY_NAME }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Terraform init
        id: tf-init
        run: terraform init

      - name: Terraform plan
        id: tf-plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform apply
        id: tf-apply
        run: terraform apply -var="image_uri=${{ env.IMAGE_TAG }}" --auto-approve
